sudo: required

language: php

php:
  - 7.2

services:
  - mysql
  - docker

addons:
  hosts:
    - nginx.symfony
    - selenium.symfony
    - prod.php.symfony
    - php.symfony
    - frontend.symfony

cache:
  yarn: true
  directories:
  - $HOME/.composer/cache/files
  - node_modules

before_install:
  - cp .env.dist .env
  - echo "DATABASE_URL=mysql://root:@127.0.0.1:3306/gifts" >> .env # Last parameter is used. Updated to Travis login
  - chmod -R 0777 ./
  # Starting docker containers
  - ./start-containers.sh

install:
  - ./install-dependencies.sh

before_script:
# Get the token from github and put it in travis repo under GITHUB_COMPOSER_AUTH ENV variable, then uncomment line below.
#  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - ./setup-database.sh
  - ./load-fixtures.sh
  - ./build-frontend.sh

script:
  - docker-compose exec -T prod.php.symfony vendor/bin/phpcs -p --standard=PSR2 --extensions=php ./src
  - docker-compose exec -T prod.php.symfony bin/phpunit
  - docker-compose exec -T prod.php.symfony cd acceptance-tests && vendor/bin/codecept run --debug --env=travis

after_failure:
  - tail -n 5000 $TRAVIS_BUILD_DIR/acceptance-tests/tests/_output/*
